### PR TITLE
Fix removeCircular in IE9. Closes #247

### LINKED ISSUE #247: IE9 compatibility
When running our tests in IE9 we were getting a lot of "Function expected" errors from this library. I narrowed it down to [this line](https://github.com/js-data/js-data-http/blob/master/src/index.js#L127) of the http adapter and then browserstack started crapping out locally so I couldn't carry on running the tests. A best guess would be `(value instanceof File)` on [this line](https://github.com/js-data/js-data/blob/master/dist/js-data.js#L1195) as the File object isn't available on IE9 but I can't say for certain.

If you run your tests with browserstack on your CI in IE9 you will see a bunch of them failing with this error. [This plugin](https://github.com/karma-runner/karma-browserstack-launcher) makes it super easy to run tests on browserstack and it's free for open source.

### PR DESCRIPTION
**Pull request by mattlewis92**
Confirmed that this fixes most of the tests on IE9 :smile:

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -572,7 +572,16 @@ export default {
...
-      if (typeof value === 'object' && value !== null && !(value instanceof Boolean) && !(value instanceof Date) && !(value instanceof Number) && !(value instanceof RegExp) && !(value instanceof String) && !(value instanceof File)) {
+      if (
+        typeof value === 'object' &&
+        value !== null &&
+        !(value instanceof Boolean) &&
+        !(value instanceof Date) &&
+        !(value instanceof Number) &&
+        !(value instanceof RegExp) &&
+        !(value instanceof String) &&
+        (typeof File === 'undefined' || !(value instanceof File))
```
Comment (jmdobry) [inline src/utils.js]: Instead of `typeof File === 'undefined'` why not just do `!File`?

Comment (mattlewis92) [inline src/utils.js]: Just stylistic preference, I can update the PR to just be !File if you'd prefer?

Comment (jmdobry) [inline src/utils.js]: Yes I think so, it will catch more edge cases.

Comment (mattlewis92) [inline src/utils.js]: Fixed, although I just noticed [this](https://github.com/js-data/js-data/blob/master/src/utils.js#L40) which is the actual cause of the bug (it will always be undefined in IE9 rather than throwing an error because you're accessing it on the window variable). I think this should just be removed and my check kept in place, as shadowing global variables in JS isn't good practise and can cause weird behaviour in bad JS engines like IE. What do you think?

**Comment by jmdobry** [comment]
I don't understand why the build is failing

**Comment by jmdobry** [comment]
Ah, CircleCI suppresses the export of environment variables on fork PR builds

**Comment by mattlewis92** [comment]
Looks like an issue with coveralls, circleci is saying this:
"Supressing export of environment variables COVERALLS_REPO_TOKEN, COVERALLS_SERVICE_NAME fork PR builds"

**Comment by mattlewis92** [comment]
Ah beat me to it, that makes sense and it stops malicious users from sending PRs that sniff your environment variables

**Comment by jmdobry** [comment]
sync with master and I think your build will succeed

**Comment by mattlewis92** [comment]
Great stuff, thanks! :smile:
